AllCops:
  DisabledByDefault: true
  Exclude:
    - '.git/**/*'
    - '{bin,pkg,tmp,vendor}/**/*' # vendored dependencies etc.
  NewCops: enable
  RubyInterpreters:
    - ruby
    - rake
  SuggestExtensions: false
  TargetRubyVersion: 2.1

Lint:
  Enabled: true

# disable some non-linty lint cops, these are more like style checks
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# TODO: temporarily disabled because of new offenses reported on CI
Lint/UselessConstantScoping:
  Enabled: false

# ignore weird looking regexps in specs, we wanna keep those
Lint/DuplicateRegexpCharacterClassElement:
  Exclude: ['spec/**/*']
Lint/LiteralInInterpolation:
  Exclude: ['spec/**/*']
Lint/MixedRegexpCaptureTypes:
  Exclude: ['spec/**/*']
