AllCops:
  Exclude:
    - '**/vendor/**/*' # vendored dependencies
    - './tmp/**/*'
  NewCops: enable
  RubyInterpreters:
    - ruby
    - rake
  TargetRubyVersion: 2.1

# disable some non-linty lint cops, these are more like style checks
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# TODO: temporarily disabled because of new offenses reported on CI
Lint/UselessConstantScoping:
  Enabled: false

# ignore weird looking regexps in specs, we wanna keep those
Lint/DuplicateRegexpCharacterClassElement:
  Exclude: ['spec/**/*']
Lint/LiteralInInterpolation:
  Exclude: ['spec/**/*']
Lint/MixedRegexpCaptureTypes:
  Exclude: ['spec/**/*']
