# based on https://github.com/rails/rails/blob/4a78dcb/.github/workflows/rubocop.yml

name: rubocop linting

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rubocop
